[package]
name = "zybooks_auto_complete"
version = "0.2.0"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
reqwest = { version = "0.12", features = ["blocking", "gzip", "json"] }
serde_json = "1.0"
